modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/Lycoris/issues"
license = "GPLv3"

[[mods]]
modId = "lycoris"
version = "${version}"
displayName = "Lycoris"
authors = "cao_awa,Ryan100c"
description = '''
Foo!
'''
#logoFile = ""

[[dependencies.lycoris]]
modId = "neoforge"
type = "required"
versionRange = "[21.4.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lycoris]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "lycoris.mixins.json"
